# Generated by Django 2.2.3 on 2020-07-25 13:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('purpose_of_booking', models.CharField(blank=True, max_length=200)),
                ('partner_name', models.CharField(max_length=200)),
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_checkin', models.DateField(default=datetime.date.today)),
                ('time_of_checkin', models.TimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('alternate_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('auth_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_checkout', models.DateField(default=datetime.date.today)),
                ('time_of_checkout', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('checkin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management_app.CheckIn')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='customer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.Customer'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='room_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='management_app.Rooms'),
        ),
    ]
